# Generated by Django 3.0.5 on 2020-04-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200415_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bio_chemical_failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='brain_failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='day_notice',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='heart_failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='kidney_failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_edited_day_notice',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='liver_failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='lung_failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statusmeasure',
            name='status_type',
            field=models.IntegerField(choices=[(0, 'Ratio pression artérielle sur fraction inspirée'), (1, 'Noradrénaline'), (2, 'Créatinémie'), (3, 'Decubitus ventral'), (4, 'Mode ventilatoire'), (5, 'Sédation'), (6, 'Antibiotiques'), (7, 'Type de prélèvements'), (8, 'Germes'), (9, 'Curares'), (10, 'Lactatémie'), (11, 'Epuration extrarénale')]),
        ),
    ]
