# Generated by Django 3.0.5 on 2020-04-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_hospitalisation_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='NIP_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, default='["Inconnues"]', help_text='["pollen"]', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='antecedents',
            field=models.TextField(blank=True, default='{"Inconnus": ""}', help_text='json {"Cardio": "note"}̀', null=True),
        ),
    ]
