# Generated by Django 3.0.5 on 2020-04-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20200422_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hematologic_failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_edited_treatment_limitations',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment_limitations',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='statusmeasure',
            name='status_type',
            field=models.IntegerField(choices=[(0, 'Ratio pression artérielle sur fraction inspirée'), (1, 'Noradrénaline'), (2, 'Créatinémie'), (3, 'Decubitus ventral'), (4, 'Mode ventilatoire'), (5, 'Sédation'), (6, 'Antibiotiques'), (7, 'Type de prélèvements'), (8, 'Germes'), (9, 'Curares'), (10, 'Lactatémie'), (11, 'Epuration extrarénale'), (12, 'Taux de prothrombine'), (13, 'Adrénaline'), (14, 'Dobutamine'), (15, 'Plaquettes'), (16, 'Glasgow'), (17, 'Débit de dioxygène inspiré'), (18, 'Fraction de dioxygène inspirée'), (19, 'Pression artérielle')]),
        ),
    ]
