# Generated by Django 3.0.5 on 2020-04-11 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('latitude', models.FloatField(default=48.856614)),
                ('longitude', models.FloatField(default=2.3522219)),
                ('postcode', models.CharField(max_length=50)),
                ('phone_bed_manager', models.CharField(max_length=500)),
                ('country', models.CharField(default='FRANCE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, choices=[('M', 'Médical'), ('K', 'Kinésithérapeute'), ('AS', 'Aide soignant'), ('I', 'Infirmier')], max_length=30, null=True)),
                ('authorized_reanimation_services', models.ManyToManyField(blank=True, to='beds.ReanimationService')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
